# Generated by Django 3.2.9 on 2021-11-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
    ]
