# Generated by Django 3.2.9 on 2021-11-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_remove_meetup_organizer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
